export const START_VALIDATION = 'START_VALIDATION';
export const VALIDATION_SUCCESSFULL = 'VALIDATION_SUCCESSFULL';
export const VALIDATION_FAILURE = 'VALIDATION_FAILURE';

export const START_LOGIN = 'START_LOGIN';
export const LOGIN_SUCCESSFULL = 'LOGIN_SUCCESSFULL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const START_SET_USER = 'SET_USER';
export const SET_USER = 'SET_USER';